//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdTabHome = 1011;
            public const uint cmdGroupParagraph = 1010;
            public const uint cmdDecreaseIndent = 1001;
            public const uint cmdIncreaseIndent = 1002;
            public const uint cmdStartList = 1003;
            public const uint cmdLineSpacing = 1004;
            public const uint cmdAlignLeft = 1005;
            public const uint cmdAlignCenter = 1006;
            public const uint cmdAlignRight = 1007;
            public const uint cmdJustify = 1008;
            public const uint cmdParagraph = 1009;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonTab TabHome { get; private set; }
        public RibbonGroup GroupParagraph { get; private set; }
        public RibbonButton DecreaseIndent { get; private set; }
        public RibbonButton IncreaseIndent { get; private set; }
        public RibbonButton StartList { get; private set; }
        public RibbonDropDownButton LineSpacing { get; private set; }
        public RibbonButton AlignLeft { get; private set; }
        public RibbonButton AlignCenter { get; private set; }
        public RibbonButton AlignRight { get; private set; }
        public RibbonButton Justify { get; private set; }
        public RibbonButton Paragraph { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            TabHome = new RibbonTab(ribbon, Cmd.cmdTabHome);
            GroupParagraph = new RibbonGroup(ribbon, Cmd.cmdGroupParagraph);
            DecreaseIndent = new RibbonButton(ribbon, Cmd.cmdDecreaseIndent);
            IncreaseIndent = new RibbonButton(ribbon, Cmd.cmdIncreaseIndent);
            StartList = new RibbonButton(ribbon, Cmd.cmdStartList);
            LineSpacing = new RibbonDropDownButton(ribbon, Cmd.cmdLineSpacing);
            AlignLeft = new RibbonButton(ribbon, Cmd.cmdAlignLeft);
            AlignCenter = new RibbonButton(ribbon, Cmd.cmdAlignCenter);
            AlignRight = new RibbonButton(ribbon, Cmd.cmdAlignRight);
            Justify = new RibbonButton(ribbon, Cmd.cmdJustify);
            Paragraph = new RibbonButton(ribbon, Cmd.cmdParagraph);
        }

    }
}
