//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdFontControl = 1006;
            public const uint cmdDropDownColorPicker = 1007;
            public const uint cmdButtonNew = 1001;
            public const uint cmdButtonOpen = 1002;
            public const uint cmdButtonSave = 1003;
            public const uint cmdContextMap = 1005;
        }

        // ContextPopup CommandName
        public const uint cmdContextMap = Cmd.cmdContextMap;

        public Ribbon Ribbon { get; private set; }
        public RibbonFontControl FontControl { get; private set; }
        public RibbonDropDownColorPicker DropDownColorPicker { get; private set; }
        public RibbonButton ButtonNew { get; private set; }
        public RibbonButton ButtonOpen { get; private set; }
        public RibbonButton ButtonSave { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            FontControl = new RibbonFontControl(ribbon, Cmd.cmdFontControl);
            DropDownColorPicker = new RibbonDropDownColorPicker(ribbon, Cmd.cmdDropDownColorPicker);
            ButtonNew = new RibbonButton(ribbon, Cmd.cmdButtonNew);
            ButtonOpen = new RibbonButton(ribbon, Cmd.cmdButtonOpen);
            ButtonSave = new RibbonButton(ribbon, Cmd.cmdButtonSave);
        }

    }
}
