//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdTabMain = 1011;
            public const uint cmdGroupButtons = 1013;
            public const uint cmdButton = 1001;
            public const uint cmdToggleButton = 1002;
            public const uint cmdDropDown = 1004;
            public const uint cmdButtonDropA = 1008;
            public const uint cmdButtonDropB = 1009;
            public const uint cmdButtonDropC = 1010;
            public const uint cmdGroupCheckBox = 1014;
            public const uint cmdCheckBox = 1003;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonTab TabMain { get; private set; }
        public RibbonGroup GroupButtons { get; private set; }
        public RibbonButton Button { get; private set; }
        public RibbonToggleButton ToggleButton { get; private set; }
        public RibbonDropDownButton DropDown { get; private set; }
        public RibbonButton ButtonDropA { get; private set; }
        public RibbonButton ButtonDropB { get; private set; }
        public RibbonButton ButtonDropC { get; private set; }
        public RibbonGroup GroupCheckBox { get; private set; }
        public RibbonCheckBox CheckBox { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            TabMain = new RibbonTab(ribbon, Cmd.cmdTabMain);
            GroupButtons = new RibbonGroup(ribbon, Cmd.cmdGroupButtons);
            Button = new RibbonButton(ribbon, Cmd.cmdButton);
            ToggleButton = new RibbonToggleButton(ribbon, Cmd.cmdToggleButton);
            DropDown = new RibbonDropDownButton(ribbon, Cmd.cmdDropDown);
            ButtonDropA = new RibbonButton(ribbon, Cmd.cmdButtonDropA);
            ButtonDropB = new RibbonButton(ribbon, Cmd.cmdButtonDropB);
            ButtonDropC = new RibbonButton(ribbon, Cmd.cmdButtonDropC);
            GroupCheckBox = new RibbonGroup(ribbon, Cmd.cmdGroupCheckBox);
            CheckBox = new RibbonCheckBox(ribbon, Cmd.cmdCheckBox);
        }

    }
}
