//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdTabMain = 1000;
            public const uint cmdGroupDropDownGallery = 1001;
            public const uint cmdDropDownGallery = 1002;
            public const uint cmdCommandSpace = 1003;
            public const uint cmdGroupSplitButtonGallery = 1004;
            public const uint cmdSplitButtonGallery = 1005;
            public const uint cmdGroupInRibbonGallery = 1006;
            public const uint cmdInRibbonGallery = 1007;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonTab TabMain { get; private set; }
        public RibbonGroup GroupDropDownGallery { get; private set; }
        public RibbonDropDownGallery DropDownGallery { get; private set; }
        public RibbonButton CommandSpace { get; private set; }
        public RibbonGroup GroupSplitButtonGallery { get; private set; }
        public RibbonSplitButtonGallery SplitButtonGallery { get; private set; }
        public RibbonGroup GroupInRibbonGallery { get; private set; }
        public RibbonInRibbonGallery InRibbonGallery { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            TabMain = new RibbonTab(ribbon, Cmd.cmdTabMain);
            GroupDropDownGallery = new RibbonGroup(ribbon, Cmd.cmdGroupDropDownGallery);
            DropDownGallery = new RibbonDropDownGallery(ribbon, Cmd.cmdDropDownGallery);
            CommandSpace = new RibbonButton(ribbon, Cmd.cmdCommandSpace);
            GroupSplitButtonGallery = new RibbonGroup(ribbon, Cmd.cmdGroupSplitButtonGallery);
            SplitButtonGallery = new RibbonSplitButtonGallery(ribbon, Cmd.cmdSplitButtonGallery);
            GroupInRibbonGallery = new RibbonGroup(ribbon, Cmd.cmdGroupInRibbonGallery);
            InRibbonGallery = new RibbonInRibbonGallery(ribbon, Cmd.cmdInRibbonGallery);
        }

    }
}
