//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdTabDrop = 1012;
            public const uint cmdGroupDrop = 1015;
            public const uint cmdButtonDropA = 1008;
            public const uint cmdButtonDropB = 1009;
            public const uint cmdButtonDropC = 1010;
            public const uint cmdGroupMore = 1017;
            public const uint cmdSpinner = 1018;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonTab TabDrop { get; private set; }
        public RibbonGroup GroupDrop { get; private set; }
        public RibbonButton ButtonDropA { get; private set; }
        public RibbonButton ButtonDropB { get; private set; }
        public RibbonButton ButtonDropC { get; private set; }
        public RibbonGroup GroupMore { get; private set; }
        public RibbonSpinner Spinner { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            TabDrop = new RibbonTab(ribbon, Cmd.cmdTabDrop);
            GroupDrop = new RibbonGroup(ribbon, Cmd.cmdGroupDrop);
            ButtonDropA = new RibbonButton(ribbon, Cmd.cmdButtonDropA);
            ButtonDropB = new RibbonButton(ribbon, Cmd.cmdButtonDropB);
            ButtonDropC = new RibbonButton(ribbon, Cmd.cmdButtonDropC);
            GroupMore = new RibbonGroup(ribbon, Cmd.cmdGroupMore);
            Spinner = new RibbonSpinner(ribbon, Cmd.cmdSpinner);
        }

    }
}
