//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdTab = 999;
            public const uint cmdButtonsGroup = 1000;
            public const uint cmdButtonListColors = 1006;
            public const uint cmdDropDownColorPickerGroup = 1001;
            public const uint cmdDropDownColorPickerThemeColors = 1002;
            public const uint cmdDropDownColorPickerStandardColors = 1003;
            public const uint cmdDropDownColorPickerHighlightColors = 1004;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonTab Tab { get; private set; }
        public RibbonGroup ButtonsGroup { get; private set; }
        public RibbonButton ButtonListColors { get; private set; }
        public RibbonGroup DropDownColorPickerGroup { get; private set; }
        public RibbonDropDownColorPicker DropDownColorPickerThemeColors { get; private set; }
        public RibbonDropDownColorPicker DropDownColorPickerStandardColors { get; private set; }
        public RibbonDropDownColorPicker DropDownColorPickerHighlightColors { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            Tab = new RibbonTab(ribbon, Cmd.cmdTab);
            ButtonsGroup = new RibbonGroup(ribbon, Cmd.cmdButtonsGroup);
            ButtonListColors = new RibbonButton(ribbon, Cmd.cmdButtonListColors);
            DropDownColorPickerGroup = new RibbonGroup(ribbon, Cmd.cmdDropDownColorPickerGroup);
            DropDownColorPickerThemeColors = new RibbonDropDownColorPicker(ribbon, Cmd.cmdDropDownColorPickerThemeColors);
            DropDownColorPickerStandardColors = new RibbonDropDownColorPicker(ribbon, Cmd.cmdDropDownColorPickerStandardColors);
            DropDownColorPickerHighlightColors = new RibbonDropDownColorPicker(ribbon, Cmd.cmdDropDownColorPickerHighlightColors);
        }

    }
}
