//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdQAT = 1006;
            public const uint cmdButtonNew = 1001;
            public const uint cmdButtonOpen = 1002;
            public const uint cmdButtonSave = 1003;
            public const uint cmdTabMain = 1004;
            public const uint cmdGroupFileActions = 1005;
            public const uint cmdCustomizeQAT = 1007;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonQuickAccessToolbar QAT { get; private set; }
        public RibbonButton ButtonNew { get; private set; }
        public RibbonButton ButtonOpen { get; private set; }
        public RibbonButton ButtonSave { get; private set; }
        public RibbonTab TabMain { get; private set; }
        public RibbonGroup GroupFileActions { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            QAT = new RibbonQuickAccessToolbar(ribbon, Cmd.cmdQAT, Cmd.cmdCustomizeQAT);
            ButtonNew = new RibbonButton(ribbon, Cmd.cmdButtonNew);
            ButtonOpen = new RibbonButton(ribbon, Cmd.cmdButtonOpen);
            ButtonSave = new RibbonButton(ribbon, Cmd.cmdButtonSave);
            TabMain = new RibbonTab(ribbon, Cmd.cmdTabMain);
            GroupFileActions = new RibbonGroup(ribbon, Cmd.cmdGroupFileActions);
        }

    }
}
